FROM node:22-bookworm-slim

WORKDIR /app

COPY package*.json tsconfig.json ./
COPY packages/db/package*.json ./packages/db/
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/

RUN npm install --legacy-peer-deps
